### ISSUE TITLE
Cloudformation deployment failed: AMI does not exist

### ISSUE THREAD

**Issue by ryan-at-work** [cxzczxzc/cloud-competition-repo#1]
@hdossani - cloudformation deployment failed with error:

The image id '[ami-04581fbf744a7d11f]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: a4d85cc5-cf0c-4be0-bf69-b5cdaecf4f5c; Proxy: null)"

![2023-04-02_cf-error1](https://user-images.githubusercontent.com/128000485/229397037-7799747f-cccd-4cef-a992-7fa5ca92c1d4.png)

Eventually found a flaskapp-ami-image and substituted this in the template file

![2023-04-02_ami-image1](https://user-images.githubusercontent.com/128000485/229396902-ac2d715b-9e2d-479a-aa9e-3534e431fbaa.png)

```
suarezry@dev-sheridan:~/awsCompetition/cloud-competition-repo/CloudFormation$ tail competition-stack.yml

  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: EC2SecurityGroup
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0e8a20c6da2c1ffbe
      Tags: 
      - Key: Name
        Value: !Sub ${AWS::StackName}-ec2
```
